---
# tasks file for ansible-role-tensorflow-gpu
- name: Trust packaging key for Nvidia repositories (apt)
  apt_key:
    data: "{{ lookup('file', 'files/nvidia_packaging_key.asc') }}"
    id: "{{ nvidia_packaging_key_id }}"
    state: present

- name: Configure Nvidia CUDA repository (apt)
  apt_repository:
    repo: "deb {{ cuda_repo_url }}/{{ nvidia_repo_subfolder }}/x86_64 /"
    filename: nvidia
    state: present

- name: Configure Nvidia machine learning repository (apt)
  apt_repository:
    repo: "deb {{ machine_learning_repo_url }}/{{ nvidia_repo_subfolder }}/x86_64 /"
    filename: nvidia
    state: present

# vim:ft=ansible:
