---
# handlers file for ansible-role-tensorflow-gpu
- name: reload systemd unit files
  command: systemctl daemon-reload
  when: ansible_connection != 'chroot'

- name: Initialize the GPUs
  command: /bin/bash /usr/local/bin/nvidia_init.sh
  when:
    - nvidia_init|bool
    - nvidia_init_restart_service|bool
    - ansible_connection != 'chroot'

- name: Restart nvidia_init service
  service:
    name: nvidia_init
    state: restarted
  when:
    - nvidia_init|bool
    - nvidia_init_restart_service|bool
    - ansible_service_mgr == "systemd"

- name: ZZ Nvidia Restart server
  command: sleep 2 && /sbin/shutdown -r now "Node software upgrade reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when:
    - nvidia_packages_installation.changed
    - nvidia_restart_node_on_install|bool
    - ansible_connection != 'chroot'

# define the variable running_as_ansible_pull in the ansible-pull playbook, like local.yml
- name: ZZ Nvidia Wait for server to restart
  wait_for:
    host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    state: started
    delay: 30
    timeout: 300
  connection: local
  become: false
  when:
    - nvidia_restart_node_on_install|bool
    - (running_as_ansible_pull is not defined or not running_as_ansible_pull)
    - ansible_connection != 'chroot'

# vim:ft=ansible:
